# Pre-commit that runs locally
fail_fast: false

# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v5.0.0
#     hooks:
#       - id: trailing-whitespace
#       - id: check-yaml

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v4.0.0-alpha.8
  #   hooks:
  #     - id: prettier
  #       files: '\.(yaml|yml)$'

  # - repo: https://github.com/psf/black
  #   rev: 24.8.0
  #   hooks:
  #     - id: black
  #       language_version: python3.11

  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.1.2
  #   hooks:
  #     - id: flake8

  # - repo: https://github.com/tconbeer/sqlfmt
  #   rev: v0.26.0
  #   hooks:
  #     - id: sqlfmt
  #       files: ^(models|analyses|tests)/.*.sql$
